In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display
import datetime
import time
import math
import warnings
warnings.filterwarnings("ignore")
import glob
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv('House3.csv')
df

1380136869   387  0  0.1  86  0.2  0.3   0.4  145  0.5  0.6
0        1380136875   386  0    0  86    0    0     0  144    0    0
1        1380136882   383  0    0  86    0    0     0  144    0    0
2        1380136890   388  0    0  87    0    0     0  145    0    0
3        1380136897   388  0    0  86    0    0     0  145    0    0
4        1380136903   388  0    0  20    0    0     0  145    0    0
...             ...   ... ..  ...  ..  ...  ...   ...  ...  ...  ...
7694942  1433238914  2674  0    0   0    0    0  1994    0    0    0
7694943  1433238921  2435  0    0   0    0    0  1841    0    0    0
7694944  1433238928  2453  0    0   0    0    0  1828    0    0    0
7694945  1433238935  2733  0    0   0    0    0  1972    0    0    0
7694946  1433238942  2638  0    0   0    0    0     3    0    0    0

[7694947 rows x 11 columns]

In [3]:
df['Time'] = pd.to_datetime(df['1380136869'], unit='s')
df.head(10)

1380136869  387  0  0.1  86  0.2  0.3  0.4  145  0.5  0.6  \
0  1380136875  386  0    0  86    0    0    0  144    0    0   
1  1380136882  383  0    0  86    0    0    0  144    0    0   
2  1380136890  388  0    0  87    0    0    0  145    0    0   
3  1380136897  388  0    0  86    0    0    0  145    0    0   
4  1380136903  388  0    0  20    0    0    0  145    0    0   
5  1380136910  324  0    0  20    0    0    0  144    0    0   
6  1380136917  325  0    0  20    0    0    0  145    0    0   
7  1380136925  325  0    0   0    0    0    0  144    0    0   
8  1380136929  324  0    0   0    0    0    0  144    0    0   
9  1380136932  324  0    0   0    0    0    0  144    0    0   

                 Time  
0 2013-09-25 19:21:15  
1 2013-09-25 19:21:22  
2 2013-09-25 19:21:30  
3 2013-09-25 19:21:37  
4 2013-09-25 19:21:43  
5 2013-09-25 19:21:50  
6 2013-09-25 19:21:57  
7 2013-09-25 19:22:05  
8 2013-09-25 19:22:09  
9 2013-09-25 19:22:12

In [4]:
# According to documentation, for House 2 of REFIT dataset,
# First Column - Aggregate Power
# Third Column - Fridge
# Sixth Column - Dishwasher
# Seventh Column - Washing Machine
# Ninth Column - Microwave

In [5]:
df = df.rename(columns={'387': 'Mains', '0.1':'Fridge', '0.4':'Washer_Dryer', '0.3':'Dishwasher', '0.5':'Microwave'})
df = df[['Time', 'Mains', 'Fridge','Washer_Dryer','Dishwasher','Microwave']]
df

Time  Mains  Fridge  Washer_Dryer  Dishwasher  \
0       2013-09-25 19:21:15    386       0             0           0   
1       2013-09-25 19:21:22    383       0             0           0   
2       2013-09-25 19:21:30    388       0             0           0   
3       2013-09-25 19:21:37    388       0             0           0   
4       2013-09-25 19:21:43    388       0             0           0   
...                     ...    ...     ...           ...         ...   
7694942 2015-06-02 09:55:14   2674       0          1994           0   
7694943 2015-06-02 09:55:21   2435       0          1841           0   
7694944 2015-06-02 09:55:28   2453       0          1828           0   
7694945 2015-06-02 09:55:35   2733       0          1972           0   
7694946 2015-06-02 09:55:42   2638       0             3           0   

         Microwave  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
7694942          0  
7694943          0  
7694944          0  
7694945          0  
7694946          0  

[7694947 rows x 6 columns]

In [6]:
df.to_csv('Refit House3.csv', index=False)

# Fridge

In [7]:
fridge = df['Fridge']
fridge = pd.DataFrame(fridge)

In [8]:
km = KMeans(n_clusters=2)
km.fit(fridge)

KMeans(n_clusters=2)

In [9]:
centroids  = km.cluster_centers_
cent_fridge=centroids
cent_fridge

array([[5.54424777e+01],
       [7.86556000e+04]])

In [10]:
lambda_fridge = sum(cent_fridge) / len(cent_fridge)

# Dishwasher

In [11]:
dw = df['Dishwasher']
dw = pd.DataFrame(dw)

In [12]:
km = KMeans(n_clusters=2)
km.fit(dw)

KMeans(n_clusters=2)

In [13]:
centroids  = km.cluster_centers_
cent_dw=centroids
cent_dw

array([[   2.43687546],
       [2127.81557813]])

In [14]:
lambda_dw = sum(cent_dw) / len(cent_dw)

# Microwave

In [15]:
mw = df['Microwave']
mw = pd.DataFrame(mw)

In [16]:
km = KMeans(n_clusters=2)
km.fit(mw)

KMeans(n_clusters=2)

In [17]:
centroids  = km.cluster_centers_
cent_mw=centroids
cent_mw

array([[2.66812243e+00],
       [7.72357143e+04]])

In [18]:
lambda_mw = sum(cent_mw) / len(cent_mw)

# Washer Dryer

In [19]:
wd = df['Washer_Dryer']
wd = pd.DataFrame(wd)

In [20]:
km = KMeans(n_clusters=2)
km.fit(wd)

KMeans(n_clusters=2)

In [21]:
centroids  = km.cluster_centers_
cent_wd=centroids
cent_wd

array([[2.90225083e+01],
       [4.80510890e+04]])

In [22]:
lambda_wd = sum(cent_wd) / len(cent_wd)

## Adding Appliance Status to the Dataframe

In [23]:
df['fridge_stats'] = df['Fridge'] - lambda_fridge
df['fridge_stat'] = [1 if x >= 0 else 0 for x in df['fridge_stats']]
df.fridge_stat

0          0
1          0
2          0
3          0
4          0
          ..
7694942    0
7694943    0
7694944    0
7694945    0
7694946    0
Name: fridge_stat, Length: 7694947, dtype: int64

In [24]:
df['dishwasher_stats'] = df['Dishwasher'] - lambda_dw
df['dishwasher_stat'] = [1 if x >= 0 else 0 for x in df['dishwasher_stats']]
df.dishwasher_stat

0          0
1          0
2          0
3          0
4          0
          ..
7694942    0
7694943    0
7694944    0
7694945    0
7694946    0
Name: dishwasher_stat, Length: 7694947, dtype: int64

In [25]:
df['microwave_stats'] = df['Microwave'] - lambda_mw
df['microwave_stat'] = [1 if x >= 0 else 0 for x in df['microwave_stats']]
df.microwave_stat

0          0
1          0
2          0
3          0
4          0
          ..
7694942    0
7694943    0
7694944    0
7694945    0
7694946    0
Name: microwave_stat, Length: 7694947, dtype: int64

In [26]:
df['washerdryer_stats'] = df['Washer_Dryer'] - lambda_wd
df['washerdryer_stat'] = [1 if x >= 0 else 0 for x in df['washerdryer_stats']]
df.washerdryer_stat

0          0
1          0
2          0
3          0
4          0
          ..
7694942    0
7694943    0
7694944    0
7694945    0
7694946    0
Name: washerdryer_stat, Length: 7694947, dtype: int64

In [27]:
df = df[['Time', 'Mains', 'fridge_stat','dishwasher_stat','microwave_stat','washerdryer_stat']]

In [28]:
df.head(5)

Time  Mains  fridge_stat  dishwasher_stat  microwave_stat  \
0 2013-09-25 19:21:15    386            0                0               0   
1 2013-09-25 19:21:22    383            0                0               0   
2 2013-09-25 19:21:30    388            0                0               0   
3 2013-09-25 19:21:37    388            0                0               0   
4 2013-09-25 19:21:43    388            0                0               0   

   washerdryer_stat  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [29]:
ddf = df.reset_index() # same as df.reset_index(level=0)
ddf.to_csv('House3 Refit with operational status (MPT).csv', index = False) # this is for house 1 of the low frequency REDD dataset