In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display
import datetime
import time
import math
import warnings
warnings.filterwarnings("ignore")
import glob
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv('House2.csv')


In [3]:
df['Time'] = pd.to_datetime(df['1379455690'], unit='s')
df.head(10)

1379455690  695  88  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  \
0  1379455698  694  88  0    0    0    0    0    0    0    0   
1  1379455705  694  88  0    0    0    0    0    0    0    0   
2  1379455714  702  88  0    0    0    0    0    0    0    0   
3  1379455722  700  88  0    0    0    0    0    0    0    0   
4  1379455729  702  88  0    0    0    0    0    0    0    0   
5  1379455737  696  88  0    0    0    0    0    0    0    0   
6  1379455746  696  88  0    0    0    0    0    0    0    0   
7  1379455750  691  87  0    0    0    0    0    0    0    0   
8  1379455753  701  88  0    0    0    0    0    0    0    0   
9  1379455759  703  88  0    0    0    0    0    0    0    0   

                 Time  
0 2013-09-17 22:08:18  
1 2013-09-17 22:08:25  
2 2013-09-17 22:08:34  
3 2013-09-17 22:08:42  
4 2013-09-17 22:08:49  
5 2013-09-17 22:08:57  
6 2013-09-17 22:09:06  
7 2013-09-17 22:09:10  
8 2013-09-17 22:09:13  
9 2013-09-17 22:09:19

In [4]:
# According to documentation, for House 2 of REFIT dataset,
# First Column - Aggregate Power
# Second Column - Fridge
# Third Column - Washing Machine
# Fourth Column - Dishwasher
# Sixth Column - Mircowave

In [5]:
df = df.rename(columns={'695': 'Mains', '88':'Fridge', '0':'Washer_Dryer', '0.1':'Dishwasher', '0.3':'Microwave'})
df = df[['Time', 'Mains', 'Fridge','Washer_Dryer','Dishwasher','Microwave']]
df

Time  Mains  Fridge  Washer_Dryer  Dishwasher  \
0       2013-09-17 22:08:18    694      88             0           0   
1       2013-09-17 22:08:25    694      88             0           0   
2       2013-09-17 22:08:34    702      88             0           0   
3       2013-09-17 22:08:42    700      88             0           0   
4       2013-09-17 22:08:49    702      88             0           0   
...                     ...    ...     ...           ...         ...   
6415347 2015-05-28 07:05:16    315      82            28           0   
6415348 2015-05-28 07:05:23    333      81            28           0   
6415349 2015-05-28 07:05:30    313      81            28           0   
6415350 2015-05-28 07:05:37    316      82            54           0   
6415351 2015-05-28 07:05:43    383      82             5           0   

         Microwave  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
6415347          0  
6415348          0  
6415349          0  
6415350          0  
6415351          0  

[6415352 rows x 6 columns]

In [6]:
df.to_csv('Refit House2.csv', index=False)

# Fridge

In [7]:
fridge = df['Fridge']
fridge = pd.DataFrame(fridge)

In [8]:
km = KMeans(n_clusters=2)
km.fit(fridge)

KMeans(n_clusters=2)

In [9]:
centroids  = km.cluster_centers_
cent_fridge=centroids
cent_fridge

array([[ 1.04210068],
       [88.51213257]])

In [10]:
labels = km.labels_
labels = pd.DataFrame (labels, columns = ['fridge_label'])

dummy = df
dummy = dummy.join(labels)

test = dummy[['Fridge','fridge_label']] 

on = test[test['fridge_label'] == 1] ## on status
on = on['Fridge'].std() 

off = test[test['fridge_label'] == 0] ## off status
off = off['Fridge'].std() 

In [11]:
d = off/(on+off)
lambda_fridge = ((1.0-d)*(cent_fridge[0]))+(d*cent_fridge[1])

# Dishwasher

In [12]:
dw = df['Dishwasher']
dw = pd.DataFrame(dw)

In [13]:
km = KMeans(n_clusters=2)
km.fit(dw)

KMeans(n_clusters=2)

In [14]:
centroids  = km.cluster_centers_
cent_dw=centroids
cent_dw

array([[   3.50168757],
       [2221.26894114]])

In [15]:
labels = km.labels_
labels = pd.DataFrame (labels, columns = ['dw_label'])

dummy = df
dummy = dummy.join(labels)

test = dummy[['Dishwasher','dw_label']] 

on = test[test['dw_label'] == 1] ## on status
on = on['Dishwasher'].std() 

off = test[test['dw_label'] == 0] ## off status
off = off['Dishwasher'].std() 

In [16]:
d = off/(on+off)
lambda_dw = ((1.0-d)*(cent_dw[0]))+(d*cent_dw[1])

# Microwave

In [17]:
mw = df['Microwave']
mw = pd.DataFrame(mw)

In [18]:
km = KMeans(n_clusters=2)
km.fit(mw)

KMeans(n_clusters=2)

In [19]:
centroids  = km.cluster_centers_
cent_mw=centroids
cent_mw

array([[3.29628149e+00],
       [7.04918571e+04]])

In [20]:
labels = km.labels_
labels = pd.DataFrame (labels, columns = ['mw_label'])

dummy = df
dummy = dummy.join(labels)

test = dummy[['Microwave','mw_label']] 

on = test[test['mw_label'] == 1] ## on status
on = on['Microwave'].std() 

off = test[test['mw_label'] == 0] ## off status
off = off['Microwave'].std() 

In [21]:
d = off/(on+off)
lambda_mw = ((1.0-d)*(cent_mw[0]))+(d*cent_mw[1])

# Washer Dryer

In [22]:
wd = df['Washer_Dryer']
wd = pd.DataFrame(wd)

In [23]:
km = KMeans(n_clusters=2)
km.fit(wd)

KMeans(n_clusters=2)

In [24]:
centroids  = km.cluster_centers_
cent_wd=centroids
cent_wd

array([[   3.61648499],
       [2079.14986413]])

In [25]:
labels = km.labels_
labels = pd.DataFrame (labels, columns = ['wd_label'])

dummy = df
dummy = dummy.join(labels)

test = dummy[['Washer_Dryer','wd_label']] 

on = test[test['wd_label'] == 1] ## on status
on = on['Washer_Dryer'].std() 

off = test[test['wd_label'] == 0] ## off status
off = off['Washer_Dryer'].std() 

In [26]:
d = off/(on+off)
lambda_wd = ((1.0-d)*(cent_wd[0]))+(d*cent_wd[1])

## Adding Appliance Status to the Dataframe

In [27]:
df['fridge_stats'] = df['Fridge'] - lambda_fridge
df['fridge_stat'] = [1 if x >= 0 else 0 for x in df['fridge_stats']]
df.fridge_stat

0          1
1          1
2          1
3          1
4          1
          ..
6415347    1
6415348    1
6415349    1
6415350    1
6415351    1
Name: fridge_stat, Length: 6415352, dtype: int64

In [28]:
df['dishwasher_stats'] = df['Dishwasher'] - lambda_dw
df['dishwasher_stat'] = [1 if x >= 0 else 0 for x in df['dishwasher_stats']]
df.dishwasher_stat

0          0
1          0
2          0
3          0
4          0
          ..
6415347    0
6415348    0
6415349    0
6415350    0
6415351    0
Name: dishwasher_stat, Length: 6415352, dtype: int64

In [29]:
df['microwave_stats'] = df['Microwave'] - lambda_mw
df['microwave_stat'] = [1 if x >= 0 else 0 for x in df['microwave_stats']]
df.microwave_stat

0          0
1          0
2          0
3          0
4          0
          ..
6415347    0
6415348    0
6415349    0
6415350    0
6415351    0
Name: microwave_stat, Length: 6415352, dtype: int64

In [30]:
df['washerdryer_stats'] = df['Washer_Dryer'] - lambda_wd
df['washerdryer_stat'] = [1 if x >= 0 else 0 for x in df['washerdryer_stats']]
df.washerdryer_stat

0          0
1          0
2          0
3          0
4          0
          ..
6415347    0
6415348    0
6415349    0
6415350    1
6415351    0
Name: washerdryer_stat, Length: 6415352, dtype: int64

In [31]:
df = df[['Time', 'Mains', 'fridge_stat','dishwasher_stat','microwave_stat','washerdryer_stat']]

In [32]:
df.head(5)

Time  Mains  fridge_stat  dishwasher_stat  microwave_stat  \
0 2013-09-17 22:08:18    694            1                0               0   
1 2013-09-17 22:08:25    694            1                0               0   
2 2013-09-17 22:08:34    702            1                0               0   
3 2013-09-17 22:08:42    700            1                0               0   
4 2013-09-17 22:08:49    702            1                0               0   

   washerdryer_stat  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [33]:
ddf = df.reset_index() # same as df.reset_index(level=0)
ddf.to_csv('House2 Refit with operational status (VST).csv', index = False) # this is for house 1 of the low frequency REDD dataset