In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display
import datetime
import time
import math
import warnings
warnings.filterwarnings("ignore")
import glob

In [2]:
house1 = pd.read_csv('House1.csv')
house1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406748 entries, 0 to 406747
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Time            406748 non-null  object 
 1   mains_1         406748 non-null  float64
 2   mains_2         406748 non-null  float64
 3   refrigerator_3  406748 non-null  float64
 4   dishwaser_4     406748 non-null  float64
 5   washer_dryer_5  406748 non-null  float64
 6   microwave_6     406748 non-null  float64
 7   washer_dryer_7  406748 non-null  float64
 8   washer_dryer_8  406748 non-null  float64
dtypes: float64(8), object(1)
memory usage: 27.9+ MB


In [3]:
dates = {}
dates = [str(time)[:10] for time in house1.Time.values]
dates = sorted(list(set(dates)))
print('House {0} data contain {1} days from {2} to {3}.'.format(1,len(dates),dates[0], dates[-1]))

House 1 data contain 23 days from 2011-04-18 to 2011-05-24.


In [4]:
house1['washer_dryer'] = house1['washer_dryer_5'] + house1['washer_dryer_7'] + house1['washer_dryer_8']
house1['mains'] = house1['mains_1']+house1['mains_2']
del house1['washer_dryer_5']
del house1['washer_dryer_7']
del house1['washer_dryer_8']
del house1['mains_1']
del house1['mains_2']
house1.head(2)

Time  refrigerator_3  dishwaser_4  microwave_6  \
0  2011-04-18 13:22:13             6.0          0.0          5.0   
1  2011-04-18 13:22:16             6.0          0.0          5.0   

   washer_dryer   mains  
0           0.0  341.03  
1           0.0  342.36

# HOUSE 1

In [5]:
from sklearn.cluster import KMeans

### Fridge

In [6]:
fridge = house1['refrigerator_3']
fridge = pd.DataFrame(fridge)

In [7]:
km = KMeans(n_clusters=2)
km.fit(fridge)

KMeans(n_clusters=2)

In [8]:
centroids  = km.cluster_centers_
cent_fridge=centroids
cent_fridge

array([[201.06403671],
       [  6.65272656]])

In [9]:
lambda_fridge = sum(cent_fridge) / len(cent_fridge)

### Dishwasher (DW)

In [10]:
dw = house1['dishwaser_4']
dw = pd.DataFrame(dw)

In [11]:
km = KMeans(n_clusters=2)
km.fit(dw)

KMeans(n_clusters=2)

In [12]:
centroids  = km.cluster_centers_
cent_dw=centroids
cent_dw

array([[   5.35537745],
       [1085.4334193 ]])

In [13]:
lambda_dw = sum(cent_dw) / len(cent_dw)

### Microwave (MW)

In [14]:
mw = house1['microwave_6']
mw = pd.DataFrame(mw)

In [15]:
km = KMeans(n_clusters=2)
km.fit(mw)

KMeans(n_clusters=2)

In [16]:
centroids  = km.cluster_centers_
cent_mw=centroids
cent_mw

array([[   4.31099539],
       [1520.22549834]])

In [17]:
lambda_mw = sum(cent_mw) / len(cent_mw)

### Washer Dryer

In [18]:
wd = house1['washer_dryer']
wd = pd.DataFrame(wd)

In [19]:
km = KMeans(n_clusters=2)
km.fit(wd)

KMeans(n_clusters=2)

In [20]:
centroids  = km.cluster_centers_
cent_wd=centroids
cent_wd

array([[2.61673342e+00],
       [2.81289642e+03]])

In [21]:
lambda_wd = sum(cent_wd) / len(cent_wd)

## Adding Appliance Status to the Dataframe

In [22]:
house1['fridge_stats'] = house1['refrigerator_3'] - lambda_fridge
house1['fridge_stat'] = [1 if x >= 0 else 0 for x in house1['fridge_stats']]
house1.fridge_stat

0         0
1         0
2         0
3         0
4         0
         ..
406743    1
406744    1
406745    1
406746    1
406747    1
Name: fridge_stat, Length: 406748, dtype: int64

In [23]:
house1['dishwasher_stats'] = house1['dishwaser_4'] - lambda_dw
house1['dishwasher_stat'] = [1 if x >= 0 else 0 for x in house1['dishwasher_stats']]
house1.dishwasher_stat

0         0
1         0
2         0
3         0
4         0
         ..
406743    0
406744    0
406745    0
406746    0
406747    0
Name: dishwasher_stat, Length: 406748, dtype: int64

In [24]:
house1['microwave_stats'] = house1['microwave_6'] - lambda_mw
house1['microwave_stat'] = [1 if x >= 0 else 0 for x in house1['microwave_stats']]
house1.microwave_stat

0         0
1         0
2         0
3         0
4         0
         ..
406743    0
406744    0
406745    0
406746    0
406747    0
Name: microwave_stat, Length: 406748, dtype: int64

In [25]:
house1['washerdryer_stats'] = house1['washer_dryer'] - lambda_wd
house1['washerdryer_stat'] = [1 if x >= 0 else 0 for x in house1['washerdryer_stats']]
house1.washerdryer_stat

0         0
1         0
2         0
3         0
4         0
         ..
406743    0
406744    0
406745    0
406746    0
406747    0
Name: washerdryer_stat, Length: 406748, dtype: int64

In [26]:
del house1['fridge_stats']
del house1['dishwasher_stats']
del house1['microwave_stats']
del house1['washerdryer_stats']

del house1['refrigerator_3']
del house1['dishwaser_4']
del house1['microwave_6']
del house1['washer_dryer']

house1

Time   mains  fridge_stat  dishwasher_stat  \
0       2011-04-18 13:22:13  341.03            0                0   
1       2011-04-18 13:22:16  342.36            0                0   
2       2011-04-18 13:22:20  342.52            0                0   
3       2011-04-18 13:22:23  342.07            0                0   
4       2011-04-18 13:22:26  341.77            0                0   
...                     ...     ...          ...              ...   
406743  2011-05-24 19:56:20  274.38            1                0   
406744  2011-05-24 19:56:23  273.69            1                0   
406745  2011-05-24 19:56:27  274.07            1                0   
406746  2011-05-24 19:56:30  274.75            1                0   
406747  2011-05-24 19:56:34  274.12            1                0   

        microwave_stat  washerdryer_stat  
0                    0                 0  
1                    0                 0  
2                    0                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
406743               0                 0  
406744               0                 0  
406745               0                 0  
406746               0                 0  
406747               0                 0  

[406748 rows x 6 columns]

In [27]:
house1.describe()

mains    fridge_stat  dishwasher_stat  microwave_stat  \
count  406748.000000  406748.000000    406748.000000   406748.000000   
mean      383.496417       0.251278         0.018112        0.011840   
std       778.299465       0.433749         0.133356        0.108167   
min        90.930000       0.000000         0.000000        0.000000   
25%       140.157500       0.000000         0.000000        0.000000   
50%       177.050000       0.000000         0.000000        0.000000   
75%       349.240000       1.000000         0.000000        0.000000   
max     11926.560000       1.000000         1.000000        1.000000   

       washerdryer_stat  
count     406748.000000  
mean           0.011796  
std            0.107967  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            0.000000  
max            1.000000

In [28]:
ddf = house1.reset_index() # same as df.reset_index(level=0)
ddf.to_csv('House1 with operational status.csv', index = False) # this is for house 1 of the low frequency REDD dataset

# HOUSE 3

In [29]:
house3 = pd.read_csv('House3.csv')
house3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376150 entries, 0 to 376149
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Time            376150 non-null  object 
 1   mains_1         376150 non-null  float64
 2   mains_2         376150 non-null  float64
 3   refrigerator_3  376150 non-null  float64
 4   dishwaser_4     376150 non-null  float64
 5   washer_dryer_5  376150 non-null  float64
 6   washer_dryer_6  376150 non-null  float64
 7   microwave_7     376150 non-null  float64
dtypes: float64(7), object(1)
memory usage: 23.0+ MB


In [30]:
dates = {}
dates = [str(time)[:10] for time in house1.Time.values]
dates = sorted(list(set(dates)))
print('House {0} data contain {1} days from {2} to {3}.'.format(1,len(dates),dates[0], dates[-1]))

House 1 data contain 23 days from 2011-04-18 to 2011-05-24.


In [31]:
house3['washer_dryer'] = house3['washer_dryer_5'] + house3['washer_dryer_6']
house3['mains'] = house3['mains_2'] + house3['mains_1']
del house3['washer_dryer_5']
del house3['washer_dryer_6']
del house3['mains_1']
del house3['mains_2']
house3

Time  refrigerator_3  dishwaser_4  microwave_7  \
0       2011-04-16 05:11:30           119.0          0.0          2.0   
1       2011-04-16 05:11:33           118.0          1.0          2.0   
2       2011-04-16 05:11:36           119.0          0.0          2.0   
3       2011-04-16 05:11:40           119.0          1.0          2.0   
4       2011-04-16 05:11:43           117.0          0.0          2.0   
...                     ...             ...          ...          ...   
376145  2011-05-31 00:19:23             8.0          3.0          1.0   
376146  2011-05-31 00:19:26             8.0          3.0          2.0   
376147  2011-05-31 00:19:30             8.0          3.0          2.0   
376148  2011-05-31 00:19:33             8.0          3.0          2.0   
376149  2011-05-31 00:19:36             7.0          3.0          2.0   

        washer_dryer   mains  
0                0.0  758.64  
1                0.0  758.13  
2                0.0  759.88  
3                0.0  759.88  
4                0.0  755.87  
...              ...     ...  
376145           0.0   17.70  
376146           0.0   17.71  
376147           0.0   17.68  
376148           0.0   17.65  
376149           0.0   17.67  

[376150 rows x 6 columns]

In [32]:
from sklearn.cluster import KMeans

In [33]:
house3.describe()

refrigerator_3    dishwaser_4    microwave_7   washer_dryer  \
count   376150.000000  376150.000000  376150.000000  376150.000000   
mean        47.659705       7.365479       8.422329      81.368424   
std         68.182648      65.860263     102.046689     592.545013   
min          0.000000       0.000000       0.000000       0.000000   
25%          0.000000       1.000000       2.000000       0.000000   
50%          1.000000       1.000000       2.000000       0.000000   
75%        116.000000       1.000000       2.000000       0.000000   
max       1582.000000     786.000000    1817.000000    5660.000000   

               mains  
count  376150.000000  
mean      445.189291  
std       731.694496  
min         1.400000  
25%       142.430000  
50%       252.140000  
75%       453.980000  
max      8059.920000

### Fridge

In [34]:
fridge = house3['refrigerator_3']
fridge = pd.DataFrame(fridge)

In [35]:
km = KMeans(n_clusters=2)
km.fit(fridge)

KMeans(n_clusters=2)

In [36]:
centroids  = km.cluster_centers_
cent_fridge=centroids
cent_fridge

array([[126.49792431],
       [  0.43144457]])

In [37]:
lambda_fridge = sum(cent_fridge) / len(cent_fridge)

### Dishwasher (DW)

In [38]:
dw = house3['dishwaser_4']
dw = pd.DataFrame(dw)

In [39]:
km = KMeans(n_clusters=2)
km.fit(dw)

KMeans(n_clusters=2)

In [40]:
centroids  = km.cluster_centers_
cent_dw=centroids
cent_dw

array([[  1.62862425],
       [736.86473595]])

In [41]:
lambda_dw = sum(cent_dw) / len(cent_dw)

### Microwave (MW)

In [42]:
mw = house3['microwave_7']
mw = pd.DataFrame(mw)

In [43]:
km = KMeans(n_clusters=2)
km.fit(mw)

KMeans(n_clusters=2)

In [44]:
centroids  = km.cluster_centers_
cent_mw=centroids
cent_mw

array([[   2.36282749],
       [1716.10827068]])

In [45]:
lambda_mw =  sum(cent_mw) / len(cent_mw)

### Washer Dryer

In [46]:
wd = house3['washer_dryer']
wd = pd.DataFrame(wd)

In [47]:
km = KMeans(n_clusters=2)
km.fit(wd)

KMeans(n_clusters=2)

In [48]:
centroids  = km.cluster_centers_
cent_wd=centroids
cent_wd

array([[   7.13361149],
       [4772.22312287]])

In [49]:
lambda_wd = sum(cent_wd) / len(cent_wd)

## Adding Appliance Status to the Dataframe

In [50]:
house3['fridge_stats'] = house3['refrigerator_3'] - lambda_fridge
house3['fridge_stat'] = [1 if x >= 0 else 0 for x in house3['fridge_stats']]
house3.fridge_stat

0         1
1         1
2         1
3         1
4         1
         ..
376145    0
376146    0
376147    0
376148    0
376149    0
Name: fridge_stat, Length: 376150, dtype: int64

In [51]:
house3['dishwasher_stats'] = house3['dishwaser_4'] - lambda_dw
house3['dishwasher_stat'] = [1 if x >= 0 else 0 for x in house3['dishwasher_stats']]
house3.dishwasher_stat

0         0
1         0
2         0
3         0
4         0
         ..
376145    0
376146    0
376147    0
376148    0
376149    0
Name: dishwasher_stat, Length: 376150, dtype: int64

In [52]:
house3['microwave_stats'] = house3['microwave_7'] - lambda_mw
house3['microwave_stat'] = [1 if x >= 0 else 0 for x in house3['microwave_stats']]
house3.microwave_stat

0         0
1         0
2         0
3         0
4         0
         ..
376145    0
376146    0
376147    0
376148    0
376149    0
Name: microwave_stat, Length: 376150, dtype: int64

In [53]:
house3['washerdryer_stats'] = house3['washer_dryer'] - lambda_wd
house3['washerdryer_stat'] = [1 if x >= 0 else 0 for x in house3['washerdryer_stats']]
house3.washerdryer_stat

0         0
1         0
2         0
3         0
4         0
         ..
376145    0
376146    0
376147    0
376148    0
376149    0
Name: washerdryer_stat, Length: 376150, dtype: int64

In [54]:
del house3['fridge_stats']
del house3['dishwasher_stats']
del house3['microwave_stats']
del house3['washerdryer_stats']

del house3['refrigerator_3']
del house3['dishwaser_4']
del house3['microwave_7']
del house3['washer_dryer']

In [55]:
house3

Time   mains  fridge_stat  dishwasher_stat  \
0       2011-04-16 05:11:30  758.64            1                0   
1       2011-04-16 05:11:33  758.13            1                0   
2       2011-04-16 05:11:36  759.88            1                0   
3       2011-04-16 05:11:40  759.88            1                0   
4       2011-04-16 05:11:43  755.87            1                0   
...                     ...     ...          ...              ...   
376145  2011-05-31 00:19:23   17.70            0                0   
376146  2011-05-31 00:19:26   17.71            0                0   
376147  2011-05-31 00:19:30   17.68            0                0   
376148  2011-05-31 00:19:33   17.65            0                0   
376149  2011-05-31 00:19:36   17.67            0                0   

        microwave_stat  washerdryer_stat  
0                    0                 0  
1                    0                 0  
2                    0                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
376145               0                 0  
376146               0                 0  
376147               0                 0  
376148               0                 0  
376149               0                 0  

[376150 rows x 6 columns]

In [56]:
house3.describe()

mains    fridge_stat  dishwasher_stat  microwave_stat  \
count  376150.000000  376150.000000    376150.000000   376150.000000   
mean      445.189291       0.374630         0.007803        0.003536   
std       731.694496       0.484028         0.087988        0.059358   
min         1.400000       0.000000         0.000000        0.000000   
25%       142.430000       0.000000         0.000000        0.000000   
50%       252.140000       0.000000         0.000000        0.000000   
75%       453.980000       1.000000         0.000000        0.000000   
max      8059.920000       1.000000         1.000000        1.000000   

       washerdryer_stat  
count     376150.000000  
mean           0.015579  
std            0.123840  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            0.000000  
max            1.000000

In [57]:
ddf = house3.reset_index() # same as df.reset_index(level=0)
ddf.to_csv('House3 with operational status.csv', index = False) # this is for house 1 of the low frequency REDD dataset